Fix TypeError saving calling LogEntry.objects.log_actions()
Fix this error on Django 5.1.7:

```
  File "/.../import_export/admin.py", line 596, in _create_log_entry
    LogEntry.objects.log_actions(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        user_pk,
        ^^^^^^^^
    ...<3 lines>...
        single_object=len(rows) == 1,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: LogEntryManager.log_actions() got an unexpected keyword argument 'single_object'
```

This is caused by Django 5.1.7 making a backwards-incompatible change to `log_actions()`, dropping the `single_object` argument, for [Ticket #36217](https://code.djangoproject.com/ticket/36217) in https://github.com/django/django/pull/19214 . The fix here conditionally passes that argument on versions where it is required.